version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            - APP_NAME=YourAppName
            - APP_ENV=local
            - APP_KEY=base64:YourGeneratedAppKey
            - APP_DEBUG=true
            - APP_URL=http://localhost
            - LOG_CHANNEL=stack
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=your_database_name
            - DB_USERNAME=your_database_username
            - DB_PASSWORD=your_database_password
        volumes:
            - .:/var/www/html
        networks:
            - backend
        depends_on:
            - mysql

    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_HOST=%
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ALLOW_EMPTY_PASSWORD=1
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - backend

    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin'
        ports:
            - 8080:80
        networks:
            - backend
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=${DB_USERNAME}
            - PMA_PASSWORD=${DB_PASSWORD}
        depends_on:
            - mysql

networks:
    backend:

volumes:
    mysql_data:
        driver: local
